name: DuckDB-JDBC Alpine Compilation

on:
  workflow_dispatch:  
  push:
    branches: [ main ]
  pull_request:

jobs:
  java-alpine-amd64:
    name: Java Linux (Alpine x86_64)
    runs-on: ubuntu-latest
    container:
      image: alpine:latest 
    env:
      GEN: ninja
      DUCKDB_PLATFORM: linux_amd64
    
    steps:
      - name: Prepare Alpine Container
        shell: sh

        run: |
          # Update package lists and install essential build tools
          apk update

          apk add --no-cache build-base gcc g++ libstdc++ cmake make ninja git pkgconfig boost-dev openjdk17 openjdk17-jdk
          
          rm -rf /var/cache/apk/*

          # Set Java environment variables
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk" >> $GITHUB_ENV
          echo "/usr/lib/jvm/java-17-openjdk/bin:${PATH}" >> $GITHUB_PATH

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Compiler Flags (Optional)
        run: |
          echo "CXXFLAGS=-Wno-stringop-overflow -Wno-return-local-addr -DICU_DISABLE_WARNINGS" >> $GITHUB_ENV
          echo "CFLAGS=-Wno-stringop-overflow" >> $GITHUB_ENV

      - name: Build DuckDB JDBC
        run: |
          # Add any specific build commands for DuckDB-JDBC
          # This might need adjustment based on your specific build process
          echo $CFLAGS
          echo $CXXFLAGS
          make release

      - name: Package JDBC Artifact
        run: |
          # Copy or rename the JDBC jar as needed
          cp build/release/duckdb_jdbc.jar duckdb_jdbc-linux-alpine-x86_64.jar

      - uses: actions/upload-artifact@v4
        with:
          name: java-alpine-amd64
          path: build/release/duckdb_jdbc.jar